# Generated by Django 3.0.4 on 2020-04-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200329_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='id',
        ),
        migrations.AddField(
            model_name='chats',
            name='requested_reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='chat_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='python-telegram-bot chat id'),
        ),
    ]
